version: "3"

services:
    client:
        build: ./client
        expose: 
            - 3000
        env_file:
            - ./client/.env
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
        command: npm start
    server:
        build: ./server
        expose: 
            - 4000
        env_file:
            - ./server/.env
        ports:
            - "4000:4000"
        volumes:
            - ./server:/api
        command: npm start
